// Generated by eve. Do not edit by hand.

import * as module_0 from "../../../agent/agent.ts";
import * as module_1 from "../../../agent/channels/eve.ts";
import * as module_2 from "../../../agent/tools/analyze_reddit_data.ts";
import * as module_3 from "../../../agent/tools/generate_content_from_prompt.ts";
import * as module_4 from "../../../agent/tools/generate_content_ideas.ts";
import * as module_5 from "../../../agent/tools/get_competitive_data.ts";
import * as module_6 from "../../../agent/tools/scan_subreddit.ts";
import * as module_7 from "../../../agent/tools/search_reddit.ts";
import * as module_8 from "../../../agent/tools/suggest_subreddits.ts";
import * as module_9 from "../../../agent/subagents/image_designer/agent.ts";
import * as module_10 from "../../../agent/subagents/image_designer/tools/generate_platform_image.ts";
import * as module_11 from "../../../agent/subagents/image_designer/tools/list_product_assets.ts";
import * as module_12 from "../../../agent/subagents/image_designer/tools/remove_background.ts";
import * as module_13 from "../../../agent/subagents/image_designer/tools/review_image.ts";
import * as module_14 from "../../../agent/subagents/image_designer/tools/search_brand_guidelines.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "tools/analyze_reddit_data.ts": module_2,
                  "tools/generate_content_from_prompt.ts": module_3,
                  "tools/generate_content_ideas.ts": module_4,
                  "tools/get_competitive_data.ts": module_5,
                  "tools/scan_subreddit.ts": module_6,
                  "tools/search_reddit.ts": module_7,
                  "tools/suggest_subreddits.ts": module_8
                })
            }),
      "subagents/image_designer": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_9,
                  "tools/generate_platform_image.ts": module_10,
                  "tools/list_product_assets.ts": module_11,
                  "tools/remove_background.ts": module_12,
                  "tools/review_image.ts": module_13,
                  "tools/search_brand_guidelines.ts": module_14
                })
            })
    })
});

export default moduleMap;
